# Detached Duplex Lagos
db_link_1 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype"
db_link_2 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=2"
db_link_3 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=3"
db_link_4 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=4"
db_link_5 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=5"
db_link_6 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=6"
db_link_7 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=7"
db_link_8 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=8"
db_link_9 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=9"
db_link_10 = "https://nigeriapropertycentre.com/for-sale/houses/detached-duplexes/lagos/showtype?page=10"